import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int Rep = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int sim_count = 0; 

		boolean IsABoy = false; //This variable will become true when a boy is born.
		boolean IsAGirl = false; //This variable will become true when a girl is born.
		double Birth =  generator.nextDouble(); //This variable holds the results of the birth.
		int child_count = 0; //This variable counts how many children were born inside the current simulation. 
		double Allchildren = 0; //This variable counts how many children were totally born. 
		double Avarage = 0.0;

		//variables that count the amount of families with 2, 3 ,4/more childrens 
		int fam2_count = 0;
		int fam3_count = 0;
		int fam4_count = 0;

		while(sim_count < Rep)
		{
			IsABoy = false;
			IsAGirl = false; // restes the 3 Variabeles in the start of each simulation
			child_count = 0;
			while (IsABoy == false || IsAGirl == false) {
				child_count +=1;
				Allchildren +=1;
				if(Birth <= 0.5){ //checks if a boy or a girl was born.
					IsAGirl = true;
				}
				else{
					IsABoy = true;
				}
				Birth = generator.nextDouble();
			}
			//checks how many children were in the family and updates the counters.
			if (child_count == 2) {
				fam2_count += 1;
			}
			else if (child_count ==3) {
				fam3_count +=1;
			}
			else{
				fam4_count +=1;
			}

			sim_count +=1;
		}
		Avarage = (double)(Allchildren/Rep); //Average of how many children were born untill each family had a b oy and a girl. 
		System.out.println("Average: " + Avarage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + fam2_count);
		System.out.println("Number of families with 3 children: " + fam3_count);
		System.out.println("Number of families with 4 or more children: " + fam4_count);
		if(fam2_count > fam3_count && fam2_count > fam4_count) {
			System.out.println("The most common number of children is 2.");
		}
		else if (fam3_count > fam2_count && fam3_count > fam4_count) {
			System.out.println("The most common number of children is 3.");
		}
		else{
			System.out.println("The most common number of children is 4 or more.");
		}



		    
	}
}
